%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 2048
image_height: 1536
projection_parameters:
   mu: 1058.4010918263214
   mv: 1058.5035544505658
   u0: 1029.3052164899436
   v0: 717.0103196643621
   k2: -0.03124164248538125
   k3: -0.02633329423472931
   k4: 0.03894424132096168
   k5: -0.019217878957815994


