%YAML:1.0
---
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 2048
image_height: 1536
projection_parameters:
   mu: 1057.8085759554679
   mv: 1057.8344071878955
   u0: 1031.0394456453769
   v0: 727.7604933179784
   k2: -0.03999018098363963
   k3: 0.0035531756082936186
   k4: -0.0006681279528559426
   k5: -0.0009677749839773924


