%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1 

imu_topic: "/ms/imu/data"
image0_topic: "/forwardLeft/image_raw"
output_path: "/root/catkin_ws/output"

cam0_calib: "basler_left_forward.yaml"
image_width: 2048
image_height: 1536
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0521232345, -0.0073054379, 0.9986139389, 0.1219040939,
          -0.9986040017, -0.0089493528, 0.0520572461, 0.0366053924,
          0.0085566474, -0.9999332676, -0.0077617087, -0.0562970105,
          0.0,0.0,0.0,1.0]


#Multiple thread support
multiple_thread: 4        # origin 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time origin 0.04
max_num_iterations: 8  # max solver itrations, to guarantee real time origin 8
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       
# The raw calibrated imu intrinsics only take stationary properties into account, to conduct 
# real-world testing, some other processes will also happen, including temperature drift, motional effects, etc.
# So we recommend to increase the white_noise to several to 10x to relax these errors.
# Directly try the following params that we have successfully tested.
acc_n: 0.001093618          # accelerometer measurement noise standard deviation. 
gyr_n: 0.00060369579         # gyroscope measurement noise standard deviation.     
acc_w: 4.584471e-05        # accelerometer bias random work noise standard deviation.  
gyr_w: 3.22094e-05       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
# td: 0.009160379134269684            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
td: 0            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/root/catkin_ws/output/pose_graph" # save and load path
save_image: 1                  # save image in pose graph for visualization prupose; you can close this function by setting 0 
